version: 2
jobs:
  build:
    parallelism: 1
    environment:
      CIRCLE_ENV: test

    docker:
      - image: circleci/ruby:2.6.6-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle

    steps:
      - checkout

      - add_ssh_keys:
        fingerprints:
          - "7c:7a:23:b2:a3:41:bf:15:7d:1d:75:bb:f2:1f:59:4b"

      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - type: shell
        command: bundle exec rspec $(circleci tests glob "spec/**/*_spec.rb")

      - store_test_results:
          path: test_results
